name: "dockercicd"

on:
  push:
    branches: ["main"]
  #pull_request:
    #branches: ["main"]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Set Up Go !!'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.15'

      - name: 'Build'
        run: 'go build -v ./...'

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ secrets.DOCKERHUB.USERNAME }}
          password: ${{ secrets.DOCKERHUB.TOKEN }}

      - name: 'Build and Release to DockerHUB'
        env:
          NAME: 'kiel0103'
          REPO: 'docker-cicd'
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest

